# ###Getting single item from the database
# GET http://localhost:8080/employee

# ###Create contact or inseting an item into the database
# POST http://localhost:8080/employee HTTP/1.1
# Content-Type: application/json

# {
#     "firstName": "Benard",
#     "lastName": "Stanley",
#     "email": "benaone@gmail.com",
#     "gender": "Male",
#     "birthday": "09/02/2017",
#     "age": 23,
#     "year": "2023",
#     "semester": "Two",
#     "grade": "B+"
# }


# ### Updating Employee records in the database
# PUT http://localhost:8080/employee/63d80544028a938be1aff426 HTTP/1.1
# Content-Type: application/json

# {
#     "firstName": "Kenney",
#     "lastName": "Obowya",
#     "email": "kow=bwoya@gmail.com",
#     "gender": "male",
#     "birthday": "09/02/2017",
#     "age": 232,
#     "year": "2356",
#     "semester": "Two",
#     "grade": "B+"
# }

# ### Deleting item using a rest API By ID to the record
# DELETE http://localhost:8080/employee/63d8055a028a938be1aff427 HTTP/1.1


###Getting single item from the database
GET https://oneka-web-dev-wk-3-cse341-l06-api.onrender.com/employee

###Create contact or inseting an item into the database
POST https://oneka-web-dev-wk-3-cse341-l06-api.onrender.com/employee HTTP/1.1
Content-Type: application/json

{
    "firstName": "Benard",
    "lastName": "Stanley",
    "email": "benaone@gmail.com",
    "gender": "Male",
    "birthday": "09/02/2017",
    "age": 23,
    "year": "2023",
    "semester": "Two",
    "grade": "B+"
}


### Updating Employee records in the database
PUT https://oneka-web-dev-wk-3-cse341-l06-api.onrender.com/employee/63d80544028a938be1aff426 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Kenney",
    "lastName": "Obowya",
    "email": "kow=bwoya@gmail.com",
    "gender": "male",
    "birthday": "09/02/2017",
    "age": 232,
    "year": "2356",
    "semester": "Two",
    "grade": "B+"
}

### Deleting item using a rest API By ID to the record
DELETE https://oneka-web-dev-wk-3-cse341-l06-api.onrender.com/employee/63d8055a028a938be1aff427 HTTP/1.1